[package]
name = "main-app"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ollama-rs = "0.3.3"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
